<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class ExerciseSeeder extends Seeder
{
    /**
     * Seed the exercise library with realistic exercises covering all
     * muscle groups, equipment types, and difficulty levels.
     */
    public function run(): void
    {
        $exercises = [
            // ===== CHEST =====
            [
                'name' => 'Push-Up',
                'description' => 'A fundamental bodyweight exercise that targets the chest, shoulders, and triceps.',
                'instructions' => json_encode(['Start in a high plank position with hands slightly wider than shoulder-width apart.', 'Keep your body in a straight line from head to heels.', 'Lower your chest toward the floor by bending your elbows.', 'Push back up to the starting position.']),
                'muscle_group' => 'chest',
                'equipment' => 'bodyweight',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 12,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'horizontal_push',
                'primary_muscles' => ['chest'],
                'secondary_muscles' => ['triceps', 'front_delts'],
                'exercise_type' => 'compound',
                'goals' => ['general_fitness', 'fat_loss', 'endurance'],
            ],
            [
                'name' => 'Dumbbell Bench Press',
                'description' => 'A staple chest exercise using dumbbells to build strength and muscle mass in the pectorals.',
                'instructions' => json_encode(['Lie flat on a bench holding a dumbbell in each hand at chest level.', 'Press the dumbbells upward until your arms are fully extended.', 'Slowly lower the dumbbells back to chest level with control.', 'Keep your feet flat on the floor and back slightly arched.']),
                'muscle_group' => 'chest',
                'equipment' => 'dumbbell',
                'difficulty' => 'intermediate',
                'default_sets' => 4,
                'default_reps' => 10,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'horizontal_push',
                'primary_muscles' => ['chest'],
                'secondary_muscles' => ['triceps', 'front_delts'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            [
                'name' => 'Barbell Bench Press',
                'description' => 'The classic compound movement for building upper body pressing strength and chest size.',
                'instructions' => json_encode(['Lie on a flat bench and grip the barbell slightly wider than shoulder-width.', 'Unrack the bar and lower it to your mid-chest.', 'Press the bar back up to full lockout.', 'Keep your shoulder blades retracted and feet planted firmly.']),
                'muscle_group' => 'chest',
                'equipment' => 'barbell',
                'difficulty' => 'advanced',
                'default_sets' => 4,
                'default_reps' => 8,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'horizontal_push',
                'primary_muscles' => ['chest'],
                'secondary_muscles' => ['triceps', 'front_delts'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            [
                'name' => 'Cable Chest Fly',
                'description' => 'An isolation exercise using a cable machine to target the inner chest fibers.',
                'instructions' => json_encode(['Set the pulleys to shoulder height and grab a handle in each hand.', 'Step forward with one foot and lean slightly forward.', 'Bring your hands together in front of your chest in a hugging motion.', 'Slowly return to the starting position with arms wide.']),
                'muscle_group' => 'chest',
                'equipment' => 'machine',
                'difficulty' => 'intermediate',
                'default_sets' => 3,
                'default_reps' => 12,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'horizontal_push',
                'primary_muscles' => ['chest'],
                'secondary_muscles' => ['front_delts'],
                'exercise_type' => 'isolation',
                'goals' => ['muscle_gain', 'general_fitness'],
            ],
            // ===== BACK =====
            [
                'name' => 'Pull-Up',
                'description' => 'A bodyweight exercise that builds strength in the lats, biceps, and upper back.',
                'instructions' => json_encode(['Grab the pull-up bar with an overhand grip slightly wider than shoulder-width.', 'Hang with arms fully extended and engage your core.', 'Pull yourself up until your chin is above the bar.', 'Lower yourself back down with control.']),
                'muscle_group' => 'back',
                'equipment' => 'pull_up_bar',
                'difficulty' => 'intermediate',
                'default_sets' => 3,
                'default_reps' => 8,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'vertical_pull',
                'primary_muscles' => ['lats'],
                'secondary_muscles' => ['biceps', 'upper_back', 'rear_delts'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            [
                'name' => 'Barbell Bent-Over Row',
                'description' => 'A compound back exercise that builds thickness in the lats and rhomboids.',
                'instructions' => json_encode(['Stand with feet shoulder-width apart and hinge at the hips.', 'Grip the barbell with an overhand grip just outside your knees.', 'Pull the barbell toward your lower chest, squeezing your shoulder blades.', 'Lower the bar back down with control.']),
                'muscle_group' => 'back',
                'equipment' => 'barbell',
                'difficulty' => 'advanced',
                'default_sets' => 4,
                'default_reps' => 8,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'horizontal_pull',
                'primary_muscles' => ['back'],
                'secondary_muscles' => ['biceps', 'rear_delts'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            [
                'name' => 'Dumbbell Single-Arm Row',
                'description' => 'A unilateral back exercise that helps correct muscular imbalances.',
                'instructions' => json_encode(['Place one knee and hand on a bench for support.', 'Hold a dumbbell in the opposite hand with arm extended.', 'Pull the dumbbell up toward your hip, keeping elbow close to your body.', 'Lower the weight back down slowly.']),
                'muscle_group' => 'back',
                'equipment' => 'dumbbell',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 10,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'horizontal_pull',
                'primary_muscles' => ['back'],
                'secondary_muscles' => ['biceps', 'rear_delts'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'general_fitness'],
            ],
            [
                'name' => 'Resistance Band Pull-Apart',
                'description' => 'A rear delt and upper back exercise using a resistance band for posture improvement.',
                'instructions' => json_encode(['Hold a resistance band in front of you with arms extended at shoulder height.', 'Pull the band apart by squeezing your shoulder blades together.', 'Pause at full contraction with the band touching your chest.', 'Slowly return to the starting position.']),
                'muscle_group' => 'back',
                'equipment' => 'resistance_band',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 15,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'horizontal_pull',
                'primary_muscles' => ['rear_delts'],
                'secondary_muscles' => ['upper_back'],
                'exercise_type' => 'isolation',
                'goals' => ['general_fitness', 'fat_loss', 'endurance'],
            ],
            // ===== SHOULDERS =====
            [
                'name' => 'Dumbbell Overhead Press',
                'description' => 'A fundamental shoulder exercise that targets all three heads of the deltoid.',
                'instructions' => json_encode(['Sit or stand holding dumbbells at shoulder height with palms facing forward.', 'Press the dumbbells overhead until arms are fully extended.', 'Lower the dumbbells back to shoulder height with control.', 'Keep your core tight and avoid arching your back.']),
                'muscle_group' => 'shoulders',
                'equipment' => 'dumbbell',
                'difficulty' => 'intermediate',
                'default_sets' => 3,
                'default_reps' => 10,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'vertical_push',
                'primary_muscles' => ['shoulders'],
                'secondary_muscles' => ['triceps'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            [
                'name' => 'Pike Push-Up',
                'description' => 'A bodyweight exercise that emphasizes the shoulders by placing the body in an inverted V position.',
                'instructions' => json_encode(['Start in a push-up position and walk your hands back toward your feet.', 'Raise your hips to form an inverted V shape.', 'Bend your elbows and lower your head toward the floor.', 'Push back up to the starting position.']),
                'muscle_group' => 'shoulders',
                'equipment' => 'bodyweight',
                'difficulty' => 'intermediate',
                'default_sets' => 3,
                'default_reps' => 10,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'vertical_push',
                'primary_muscles' => ['shoulders'],
                'secondary_muscles' => ['triceps'],
                'exercise_type' => 'compound',
                'goals' => ['general_fitness', 'fat_loss', 'endurance'],
            ],
            [
                'name' => 'Kettlebell Press',
                'description' => 'A unilateral overhead pressing movement using a kettlebell for shoulder strength and stability.',
                'instructions' => json_encode(['Clean the kettlebell to the rack position at shoulder height.', 'Press the kettlebell overhead by extending your arm fully.', 'Keep your wrist straight and the kettlebell balanced.', 'Lower the kettlebell back to the rack position.']),
                'muscle_group' => 'shoulders',
                'equipment' => 'kettlebell',
                'difficulty' => 'advanced',
                'default_sets' => 4,
                'default_reps' => 8,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'vertical_push',
                'primary_muscles' => ['shoulders'],
                'secondary_muscles' => ['triceps'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            // ===== BICEPS =====
            [
                'name' => 'Dumbbell Bicep Curl',
                'description' => 'The classic isolation exercise for building bicep size and strength.',
                'instructions' => json_encode(['Stand with a dumbbell in each hand, arms fully extended at your sides.', 'Curl the dumbbells upward by flexing your elbows.', 'Squeeze your biceps at the top of the movement.', 'Lower the dumbbells back down slowly.']),
                'muscle_group' => 'biceps',
                'equipment' => 'dumbbell',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 12,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'accessory',
                'primary_muscles' => ['biceps'],
                'secondary_muscles' => [],
                'exercise_type' => 'isolation',
                'goals' => ['muscle_gain', 'general_fitness'],
            ],
            [
                'name' => 'Barbell Curl',
                'description' => 'A heavy compound curl using a barbell to overload the biceps.',
                'instructions' => json_encode(['Stand with feet shoulder-width apart holding a barbell with an underhand grip.', 'Curl the barbell up toward your shoulders, keeping elbows pinned to your sides.', 'Squeeze at the top and hold briefly.', 'Lower the barbell back down with control, avoiding swinging.']),
                'muscle_group' => 'biceps',
                'equipment' => 'barbell',
                'difficulty' => 'intermediate',
                'default_sets' => 3,
                'default_reps' => 10,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'accessory',
                'primary_muscles' => ['biceps'],
                'secondary_muscles' => [],
                'exercise_type' => 'isolation',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            [
                'name' => 'Chin-Up',
                'description' => 'A pull-up variation with underhand grip that heavily targets the biceps along with the back.',
                'instructions' => json_encode(['Grab the pull-up bar with an underhand (supinated) grip, hands shoulder-width apart.', 'Hang with arms fully extended.', 'Pull yourself up until your chin clears the bar.', 'Lower yourself back down with control.']),
                'muscle_group' => 'biceps',
                'equipment' => 'pull_up_bar',
                'difficulty' => 'advanced',
                'default_sets' => 3,
                'default_reps' => 8,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'vertical_pull',
                'primary_muscles' => ['lats'],
                'secondary_muscles' => ['biceps', 'upper_back', 'rear_delts'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            [
                'name' => 'Resistance Band Curl',
                'description' => 'A bicep curl performed with a resistance band, providing constant tension throughout the movement.',
                'instructions' => json_encode(['Stand on the middle of a resistance band with feet shoulder-width apart.', 'Hold both ends of the band with palms facing up.', 'Curl your hands toward your shoulders against the resistance.', 'Lower slowly back to the starting position.']),
                'muscle_group' => 'biceps',
                'equipment' => 'resistance_band',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 15,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'accessory',
                'primary_muscles' => ['biceps'],
                'secondary_muscles' => [],
                'exercise_type' => 'isolation',
                'goals' => ['general_fitness', 'fat_loss', 'endurance'],
            ],
            // ===== TRICEPS =====
            [
                'name' => 'Tricep Dip',
                'description' => 'A bodyweight exercise that targets the triceps using parallel bars or a bench.',
                'instructions' => json_encode(['Place your hands on the edge of a bench behind you, fingers facing forward.', 'Extend your legs out in front of you with heels on the floor.', 'Lower your body by bending your elbows to about 90 degrees.', 'Push back up to the starting position by straightening your arms.']),
                'muscle_group' => 'triceps',
                'equipment' => 'bodyweight',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 12,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'horizontal_push',
                'primary_muscles' => ['triceps'],
                'secondary_muscles' => ['chest', 'front_delts'],
                'exercise_type' => 'compound',
                'goals' => ['general_fitness', 'fat_loss', 'endurance'],
            ],
            [
                'name' => 'Dumbbell Overhead Tricep Extension',
                'description' => 'An isolation exercise that targets the long head of the triceps.',
                'instructions' => json_encode(['Stand or sit holding one dumbbell with both hands above your head.', 'Lower the dumbbell behind your head by bending your elbows.', 'Keep your upper arms close to your ears throughout.', 'Extend your arms back to the starting position.']),
                'muscle_group' => 'triceps',
                'equipment' => 'dumbbell',
                'difficulty' => 'intermediate',
                'default_sets' => 3,
                'default_reps' => 10,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'accessory',
                'primary_muscles' => ['triceps'],
                'secondary_muscles' => [],
                'exercise_type' => 'isolation',
                'goals' => ['muscle_gain', 'general_fitness'],
            ],
            [
                'name' => 'Cable Tricep Pushdown',
                'description' => 'A machine-based isolation exercise for the triceps using a cable stack.',
                'instructions' => json_encode(['Attach a straight or V-bar to the high pulley of a cable machine.', 'Grip the bar with an overhand grip and keep elbows pinned to your sides.', 'Push the bar down until your arms are fully extended.', 'Slowly return to the starting position without letting elbows flare.']),
                'muscle_group' => 'triceps',
                'equipment' => 'machine',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 12,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'accessory',
                'primary_muscles' => ['triceps'],
                'secondary_muscles' => [],
                'exercise_type' => 'isolation',
                'goals' => ['muscle_gain', 'general_fitness'],
            ],
            // ===== LEGS =====
            [
                'name' => 'Bodyweight Squat',
                'description' => 'A fundamental lower body exercise that targets the quadriceps, hamstrings, and glutes.',
                'instructions' => json_encode(['Stand with feet shoulder-width apart and toes slightly pointed out.', 'Push your hips back and bend your knees to lower your body.', 'Descend until your thighs are parallel to the floor or lower.', 'Drive through your heels to stand back up.']),
                'muscle_group' => 'legs',
                'equipment' => 'bodyweight',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 15,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'knee_dominant',
                'primary_muscles' => ['quadriceps'],
                'secondary_muscles' => ['glutes', 'hamstrings'],
                'exercise_type' => 'compound',
                'goals' => ['general_fitness', 'fat_loss', 'endurance'],
            ],
            [
                'name' => 'Barbell Back Squat',
                'description' => 'The king of lower body exercises, targeting quads, glutes, and hamstrings with heavy load.',
                'instructions' => json_encode(['Position the barbell on your upper traps and step back from the rack.', 'Stand with feet shoulder-width apart.', 'Bend at the hips and knees to lower into a squat.', 'Drive through your heels to return to standing.']),
                'muscle_group' => 'legs',
                'equipment' => 'barbell',
                'difficulty' => 'advanced',
                'default_sets' => 4,
                'default_reps' => 6,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'knee_dominant',
                'primary_muscles' => ['quadriceps'],
                'secondary_muscles' => ['glutes', 'hamstrings'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            [
                'name' => 'Kettlebell Goblet Squat',
                'description' => 'A squat variation holding a kettlebell at the chest, great for learning squat mechanics.',
                'instructions' => json_encode(['Hold a kettlebell by the horns at chest height, close to your body.', 'Stand with feet slightly wider than shoulder-width.', 'Squat down by pushing hips back and bending knees.', 'Keep your chest up and elbows between your knees at the bottom.']),
                'muscle_group' => 'legs',
                'equipment' => 'kettlebell',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 12,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'knee_dominant',
                'primary_muscles' => ['quadriceps'],
                'secondary_muscles' => ['glutes', 'hamstrings'],
                'exercise_type' => 'compound',
                'goals' => ['general_fitness', 'fat_loss', 'endurance'],
            ],
            [
                'name' => 'Leg Press',
                'description' => 'A machine-based compound exercise for the lower body that allows heavy loading with reduced spinal stress.',
                'instructions' => json_encode(['Sit on the leg press machine and place your feet shoulder-width apart on the platform.', 'Release the safety handles and lower the weight by bending your knees.', 'Lower until your knees are at about 90 degrees.', 'Push the platform back up without locking out your knees.']),
                'muscle_group' => 'legs',
                'equipment' => 'machine',
                'difficulty' => 'intermediate',
                'default_sets' => 4,
                'default_reps' => 10,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'knee_dominant',
                'primary_muscles' => ['quadriceps'],
                'secondary_muscles' => ['glutes', 'hamstrings'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            [
                'name' => 'Dumbbell Romanian Deadlift',
                'description' => 'A hip-hinge movement that targets the hamstrings and glutes using dumbbells.',
                'instructions' => json_encode(['Stand holding dumbbells in front of your thighs with a slight knee bend.', 'Hinge at the hips and push your glutes back.', 'Lower the dumbbells along your legs until you feel a hamstring stretch.', 'Drive your hips forward to return to standing.']),
                'muscle_group' => 'legs',
                'equipment' => 'dumbbell',
                'difficulty' => 'intermediate',
                'default_sets' => 3,
                'default_reps' => 10,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'hip_dominant',
                'primary_muscles' => ['hamstrings'],
                'secondary_muscles' => ['glutes', 'lower_back'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            // ===== CORE =====
            [
                'name' => 'Plank',
                'description' => 'An isometric core exercise that builds stability and endurance in the abdominals and lower back.',
                'instructions' => json_encode(['Start in a forearm plank position with elbows directly under shoulders.', 'Keep your body in a straight line from head to heels.', 'Engage your core and squeeze your glutes.', 'Hold the position for the prescribed duration.']),
                'muscle_group' => 'core',
                'equipment' => 'bodyweight',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 1,
                'default_duration_seconds' => 45,
                'movement_pattern' => 'core',
                'primary_muscles' => ['core'],
                'secondary_muscles' => [],
                'exercise_type' => 'isolation',
                'goals' => ['general_fitness', 'endurance'],
            ],
            [
                'name' => 'Hanging Leg Raise',
                'description' => 'An advanced core exercise performed on a pull-up bar that targets the lower abs.',
                'instructions' => json_encode(['Hang from a pull-up bar with arms fully extended.', 'Keep your legs straight and raise them until they are parallel to the floor.', 'Pause at the top and squeeze your abs.', 'Lower your legs back down with control, avoiding swinging.']),
                'muscle_group' => 'core',
                'equipment' => 'pull_up_bar',
                'difficulty' => 'advanced',
                'default_sets' => 3,
                'default_reps' => 10,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'core',
                'primary_muscles' => ['core'],
                'secondary_muscles' => [],
                'exercise_type' => 'isolation',
                'goals' => ['general_fitness', 'endurance'],
            ],
            [
                'name' => 'Kettlebell Russian Twist',
                'description' => 'A rotational core exercise using a kettlebell to target the obliques.',
                'instructions' => json_encode(['Sit on the floor with knees bent and feet slightly elevated.', 'Hold a kettlebell with both hands at chest height.', 'Lean back slightly and rotate your torso to one side.', 'Rotate to the other side, tapping the kettlebell on the floor beside you each time.']),
                'muscle_group' => 'core',
                'equipment' => 'kettlebell',
                'difficulty' => 'intermediate',
                'default_sets' => 3,
                'default_reps' => 20,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'core',
                'primary_muscles' => ['core'],
                'secondary_muscles' => [],
                'exercise_type' => 'isolation',
                'goals' => ['general_fitness', 'fat_loss', 'endurance'],
            ],
            [
                'name' => 'Cable Woodchop',
                'description' => 'A rotational core exercise using a cable machine to build functional strength in the obliques.',
                'instructions' => json_encode(['Set the cable pulley to the highest position and attach a single handle.', 'Stand sideways to the machine and grab the handle with both hands.', 'Pull the handle diagonally across your body toward the opposite knee.', 'Return to the starting position with control.']),
                'muscle_group' => 'core',
                'equipment' => 'machine',
                'difficulty' => 'intermediate',
                'default_sets' => 3,
                'default_reps' => 12,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'core',
                'primary_muscles' => ['core'],
                'secondary_muscles' => [],
                'exercise_type' => 'isolation',
                'goals' => ['general_fitness', 'fat_loss', 'endurance'],
            ],
            // ===== FULL BODY =====
            [
                'name' => 'Burpee',
                'description' => 'A high-intensity full body exercise that combines a squat, push-up, and jump into one explosive movement.',
                'instructions' => json_encode(['Stand with feet shoulder-width apart.', 'Drop into a squat position and place your hands on the floor.', 'Jump your feet back into a plank position and perform a push-up.', 'Jump your feet forward and explosively jump up with arms overhead.']),
                'muscle_group' => 'full_body',
                'equipment' => 'bodyweight',
                'difficulty' => 'intermediate',
                'default_sets' => 3,
                'default_reps' => 10,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'full_body',
                'primary_muscles' => ['quadriceps', 'chest'],
                'secondary_muscles' => ['shoulders', 'triceps', 'core'],
                'exercise_type' => 'compound',
                'goals' => ['fat_loss', 'endurance', 'general_fitness'],
            ],
            [
                'name' => 'Kettlebell Swing',
                'description' => 'A dynamic hip-hinge movement that targets the posterior chain while providing cardiovascular conditioning.',
                'instructions' => json_encode(['Stand with feet slightly wider than shoulder-width, kettlebell on the floor in front of you.', 'Hinge at the hips, grip the kettlebell, and hike it between your legs.', 'Drive your hips forward explosively to swing the kettlebell to chest height.', 'Let the kettlebell swing back between your legs and repeat.']),
                'muscle_group' => 'full_body',
                'equipment' => 'kettlebell',
                'difficulty' => 'intermediate',
                'default_sets' => 4,
                'default_reps' => 15,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'hip_dominant',
                'primary_muscles' => ['glutes', 'hamstrings'],
                'secondary_muscles' => ['lower_back', 'core', 'shoulders'],
                'exercise_type' => 'compound',
                'goals' => ['fat_loss', 'endurance', 'general_fitness'],
            ],
            [
                'name' => 'Barbell Deadlift',
                'description' => 'One of the most effective compound lifts, targeting the entire posterior chain including back, glutes, and hamstrings.',
                'instructions' => json_encode(['Stand with feet hip-width apart, barbell over mid-foot.', 'Hinge at the hips and grip the bar just outside your knees.', 'Drive through your heels, extending hips and knees simultaneously.', 'Stand fully upright with shoulders back, then reverse the movement.']),
                'muscle_group' => 'full_body',
                'equipment' => 'barbell',
                'difficulty' => 'advanced',
                'default_sets' => 4,
                'default_reps' => 5,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'hip_dominant',
                'primary_muscles' => ['hamstrings', 'glutes'],
                'secondary_muscles' => ['lower_back', 'back', 'core'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
            [
                'name' => 'Resistance Band Thruster',
                'description' => 'A full body combination exercise that pairs a squat with an overhead press using a resistance band.',
                'instructions' => json_encode(['Stand on the middle of a resistance band with feet shoulder-width apart.', 'Hold the band ends at shoulder height in a front rack position.', 'Perform a full squat, keeping your chest up.', 'As you stand up, press the band overhead in one fluid motion.']),
                'muscle_group' => 'full_body',
                'equipment' => 'resistance_band',
                'difficulty' => 'advanced',
                'default_sets' => 3,
                'default_reps' => 12,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'full_body',
                'primary_muscles' => ['quadriceps', 'shoulders'],
                'secondary_muscles' => ['glutes', 'triceps', 'core'],
                'exercise_type' => 'compound',
                'goals' => ['fat_loss', 'endurance', 'general_fitness'],
            ],
            [
                'name' => 'Dumbbell Clean and Press',
                'description' => 'An explosive full body movement combining a power clean with an overhead press using dumbbells.',
                'instructions' => json_encode(['Stand with dumbbells at your sides, feet shoulder-width apart.', 'Hinge slightly and explosively pull the dumbbells to shoulder height.', 'Catch the dumbbells at your shoulders and immediately press overhead.', 'Lower the dumbbells back to your sides with control.']),
                'muscle_group' => 'full_body',
                'equipment' => 'dumbbell',
                'difficulty' => 'advanced',
                'default_sets' => 4,
                'default_reps' => 8,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'full_body',
                'primary_muscles' => ['shoulders', 'quadriceps'],
                'secondary_muscles' => ['glutes', 'triceps', 'core', 'back'],
                'exercise_type' => 'compound',
                'goals' => ['fat_loss', 'endurance', 'general_fitness'],
            ],
            // ===== ADDITIONAL EXERCISES FOR COVERAGE =====
            [
                'name' => 'Resistance Band Lateral Raise',
                'description' => 'A shoulder isolation exercise using a resistance band to target the lateral deltoids.',
                'instructions' => json_encode(['Stand on the middle of a resistance band with feet hip-width apart.', 'Hold the band ends with palms facing your body.', 'Raise your arms out to the sides until they are parallel to the floor.', 'Lower back down with control.']),
                'muscle_group' => 'shoulders',
                'equipment' => 'resistance_band',
                'difficulty' => 'beginner',
                'default_sets' => 3,
                'default_reps' => 15,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'accessory',
                'primary_muscles' => ['shoulders'],
                'secondary_muscles' => [],
                'exercise_type' => 'isolation',
                'goals' => ['general_fitness', 'fat_loss', 'endurance'],
            ],
            [
                'name' => 'Close-Grip Barbell Bench Press',
                'description' => 'A compound pressing movement with a narrow grip that emphasizes the triceps.',
                'instructions' => json_encode(['Lie on a flat bench and grip the barbell with hands shoulder-width apart.', 'Unrack the bar and lower it to your lower chest, keeping elbows close to your body.', 'Press the bar back up to full extension.', 'Keep your wrists straight throughout the movement.']),
                'muscle_group' => 'triceps',
                'equipment' => 'barbell',
                'difficulty' => 'advanced',
                'default_sets' => 4,
                'default_reps' => 8,
                'default_duration_seconds' => 0,
                'movement_pattern' => 'horizontal_push',
                'primary_muscles' => ['triceps'],
                'secondary_muscles' => ['chest', 'front_delts'],
                'exercise_type' => 'compound',
                'goals' => ['muscle_gain', 'strength', 'general_fitness'],
            ],
        ];
        DB::table('exercises')->insert(
            array_map(function ($exercise) {
                $snakeName = Str::snake(str_replace('-', ' ', $exercise['name']));

                return array_merge($exercise, [
                    'video_path' => 'assets/videos/' . $snakeName . '.mp4',
                    'primary_muscles' => json_encode($exercise['primary_muscles']),
                    'secondary_muscles' => json_encode($exercise['secondary_muscles']),
                    'goals' => json_encode($exercise['goals']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }, $exercises)
        );
    }
}
